#!/usr/bin/env python3
"""
MongoDB Biome / Asset Schema — SD1.5 Multi-Stage Pipeline
==========================================================

NEW FIELDS vs old schema:
  creature_category  : "bipedal" | "quadruped"  (routes ControlNet model)
  generation_stage   : fine-grained sub-status for the image worker
  images             : nested dict tracking S3 keys per stage
  refine_prompt      : optional Stage-2 override prompt stored in DB

Status progression (compatible with existing TRELLIS + rig workers):
  not_started → generating → image_complete → model_complete → complete
                              ↑ sd15 worker sets this

Run this script ONCE to insert/update the test biome in MongoDB.
"""

import sys
from pymongo import MongoClient

MONGO_URI = os.getenv("MONGO_URI") or os.getenv("MONGODB_URL") or ""
DB_NAME   = "World_builder"

# ── New biome document ────────────────────────────────────────────────────────
BIOME_ID = "claude-sd15-test-001"

BIOME_DOC = {
    "_id":        BIOME_ID,
    "biome_name": "Cultivation Realm",

    "possible_structures": {
        "characters": {

            # ── Cultivation master (bipedal) ──────────────────────────────────
            "cultivation_master": {
                "character_type":    "humanoid",
                "creature_category": "bipedal",   # → OpenPose ControlNet

                # Stage-1 (structure) prompt is auto-generated by worker.
                # Stage-2 (detail) prompt is the custom override:
                "refine_prompt": (
                    "young male cultivator, layered robes, cloth belt, "
                    "stylized fantasy outfit, subtle mystical aura, "
                    "front view, white background, clean game asset"
                ),

                # Pipeline state
                "status":           "not_started",
                "generation_stage": None,

                # S3 keys populated by worker (null until generated)
                "images": {
                    "base":    None,   # Stage-1 output
                    "refined": None,   # Stage-2 output  ← TRELLIS input
                    "final":   None,   # alias for refined (set by worker)
                },

                # 3D pipeline fields (set by TRELLIS / UniRig workers)
                "model_path":  None,   # raw GLB
                "rigged_path": None,   # rigged GLB/FBX

                "quality": "good",
                "type":    "character",
            },

            # ── Shadow wolf (quadruped) ───────────────────────────────────────
            "shadow_wolf": {
                "character_type":    "quadruped",
                "creature_category": "quadruped",  # → Depth ControlNet

                "refine_prompt": (
                    "mystical shadow wolf, dark sleek fur, glowing purple markings, "
                    "fantasy beast, side view, white background, clean game asset"
                ),

                "status":           "not_started",
                "generation_stage": None,

                "images": {
                    "base":    None,
                    "refined": None,
                    "final":   None,
                },

                "model_path":  None,
                "rigged_path": None,

                "quality": "good",
                "type":    "character",
            },
        }
    },
}


def main():
    client = MongoClient(MONGO_URI)
    db = client[DB_NAME]

    # Upsert — safe to re-run
    result = db.biomes.replace_one({"_id": BIOME_ID}, BIOME_DOC, upsert=True)
    if result.upserted_id:
        print(f"Inserted new biome: {BIOME_ID}")
    else:
        print(f"Replaced existing biome: {BIOME_ID}  (matched={result.matched_count})")

    # Verify
    doc = db.biomes.find_one({"_id": BIOME_ID})
    chars = doc["possible_structures"]["characters"]
    print(f"\nCharacters in biome:")
    for name, c in chars.items():
        print(f"  {name}: type={c['character_type']}  category={c['creature_category']}  status={c['status']}")

    client.close()


if __name__ == "__main__":
    main()
