#!/usr/bin/env python3
"""
Queue a cultivation-master test task to the sd15_tasks Redis queue.
Run this locally AFTER:
  1. mongo_schema_update.py  (insert biome doc)
  2. sd15_image_worker.py running on A10  (listening on sd15_tasks)
"""

import json
import time
import uuid
import redis

REDIS_HOST = "18.207.13.85"
REDIS_PORT = 6380
QUEUE      = "sd15_tasks"

# ── Cultivation master task ───────────────────────────────────────────────────
#
# refine_prompt = Stage-2 detail override.
# Stage-1 (structure) prompt is always auto-generated by the worker
# from the creature_category template — do NOT send it here.
#
TASK = {
    "task_id":        str(uuid.uuid4()),
    "biome_id":       "claude-sd15-test-001",
    "character_name": "cultivation_master",
    "character_type": "humanoid",      # → bipedal OpenPose ControlNet

    # Stage-2 detail prompt (~22 tokens — well under 75-token CLIP limit)
    "refine_prompt": (
        "young male cultivator, layered robes, cloth belt, "
        "stylized fantasy outfit, subtle mystical aura, "
        "front view, white background, clean game asset"
    ),

    "timestamp": time.time(),          # REQUIRED — prevents orchestrator TTL deletion
}


def main():
    r = redis.Redis(host=REDIS_HOST, port=REDIS_PORT, db=0, decode_responses=True)

    r.rpush(QUEUE, json.dumps(TASK))
    print(f"Queued task → {QUEUE}")
    print(f"  task_id       : {TASK['task_id']}")
    print(f"  character     : {TASK['character_name']} ({TASK['character_type']})")
    print(f"  biome         : {TASK['biome_id']}")
    print(f"  refine_prompt : {TASK['refine_prompt']}")

    depth = r.llen(QUEUE)
    print(f"\nQueue depth now: {depth}")


if __name__ == "__main__":
    main()
