#!/usr/bin/env python3
"""
SD 1.5 Image Worker  (extends BaseWorker)
=========================================
Stage 1: SD1.5 + ControlNet → clean base structure (pose/silhouette)
Stage 2: SD1.5 img2img      → add clothing / textures / aura

ControlNet routing:
  bipedal / humanoid → lllyasviel/control_v11p_sd15_openpose  (COCO-18 T-pose)
  quadruped          → huchenlei/animal_openpose               (AP10K-17 skeleton)

Prompt strategy (CLIP ~75 token limit):
  Stage 1 — structure only: pose, proportions, plain outfit, white bg
  Stage 2 — detail pass: clothing, style, atmosphere, quality prefix
"""

import os
import time
import uuid

import torch
from PIL import Image
from diffusers import (
    ControlNetModel,
    StableDiffusionControlNetPipeline,
    StableDiffusionImg2ImgPipeline,
    UniPCMultistepScheduler,
)

from .base_worker import BaseWorker

# ── Model IDs ─────────────────────────────────────────────────────────────────
SD15_MODEL_ID          = "Lykon/DreamShaper"
CONTROLNET_OPENPOSE_ID = "lllyasviel/control_v11p_sd15_openpose"
CONTROLNET_ANIMAL_ID   = "huchenlei/animal_openpose"

# ── Reference skeleton images (generated by prepare_controlnet_refs.py) ───────
TPOSE_OPENPOSE_PATH  = os.getenv(
    "TPOSE_OPENPOSE_PATH",
    "/home/ec2-user/controlnet_refs/tpose_openpose.png",
)
QUAD_ANIMALPOSE_PATH = os.getenv(
    "QUAD_ANIMALPOSE_PATH",
    "/home/ec2-user/controlnet_refs/quad_animalpose.png",
)

# ── Generation hyper-params ───────────────────────────────────────────────────
IMG_SIZE        = 512
STAGE1_STEPS    = 25
STAGE1_CFG      = 7.5
STAGE1_CN_SCALE = 1.0
STAGE2_STEPS    = 20
STAGE2_CFG      = 7.5
STAGE2_STRENGTH = 0.35

# ── Queue names ───────────────────────────────────────────────────────────────
INPUT_QUEUE  = "sd15_tasks"
OUTPUT_QUEUE = "model_tasks"

# ── Prompt Templates (CLIP token-aware) ──────────────────────────────────────
QUALITY_PREFIX = "best quality, masterpiece, "  # ~5 tokens

CREATURE_PROMPTS = {
    "bipedal": {
        "stage1": {
            "positive": (
                "young male, athletic build, T-pose, arms extended horizontally, "
                "front view, full body, white background, flat lighting, "
                "centered, plain outfit, character sheet"
            ),
            "negative": (
                "background, shadows, complex textures, accessories, weapons, armor, "
                "text, watermark, blurry, cropped, extra limbs, deformed, nsfw"
            ),
        },
        "stage2": {
            "positive": (
                "young male cultivator, layered robes, cloth belt, "
                "stylized fantasy outfit, subtle mystical aura, "
                "front view, white background, clean game asset"
            ),
            "negative": (
                "background, photorealistic, blurry, extra limbs, "
                "text, watermark, deformed, ugly, nsfw"
            ),
        },
    },
    "quadruped": {
        "stage1": {
            "positive": (
                "four-legged creature, neutral standing pose, side view, "
                "full body, white background, flat lighting, centered, "
                "simple form, creature design sheet"
            ),
            "negative": (
                "background, shadows, complex textures, text, watermark, "
                "blurry, cropped, extra limbs, deformed, human, bipedal, nsfw"
            ),
        },
        "stage2": {
            "positive": (
                "mystical beast, detailed fur, glowing markings, "
                "fantasy creature, side view, white background, clean game asset"
            ),
            "negative": (
                "background, photorealistic, blurry, extra limbs, "
                "text, watermark, deformed, ugly, human, nsfw"
            ),
        },
    },
    "humanoid": {
        "stage1": {
            "positive": (
                "humanoid character, athletic build, T-pose, arms extended horizontally, "
                "front view, full body, white background, flat lighting, "
                "centered, plain outfit, character sheet"
            ),
            "negative": (
                "background, shadows, complex textures, accessories, weapons, "
                "text, watermark, blurry, cropped, extra limbs, deformed, nsfw"
            ),
        },
        "stage2": {
            "positive": (
                "humanoid character, detailed outfit, stylized fantasy costume, "
                "front view, white background, clean game asset, high detail"
            ),
            "negative": (
                "background, photorealistic, blurry, extra limbs, "
                "text, watermark, deformed, ugly, nsfw"
            ),
        },
    },
}


def build_prompt(template: str, custom_override: str | None, max_tokens: int = 68) -> str:
    """Prepend quality prefix; optionally use custom override. Truncate to max_tokens."""
    base  = QUALITY_PREFIX + (custom_override if custom_override else template)
    words = base.split()
    if len(words) * 1.3 > max_tokens:
        words = words[:int(max_tokens / 1.3)]
    return " ".join(words)


class SD15Worker(BaseWorker):
    """SD1.5 + ControlNet two-stage character image generator."""

    worker_name = "SD15Worker"
    input_queue = INPUT_QUEUE

    def __init__(self):
        super().__init__()
        self.controlnet_openpose = None
        self.controlnet_animal   = None
        self.pipe_cn             = None
        self.pipe_i2i            = None

    # ── Model Loading ─────────────────────────────────────────────────────────

    def load_models(self):
        self.logger.info("Loading ControlNet models...")
        self.controlnet_openpose = ControlNetModel.from_pretrained(
            CONTROLNET_OPENPOSE_ID, torch_dtype=torch.float16
        )
        self.controlnet_animal = ControlNetModel.from_pretrained(
            CONTROLNET_ANIMAL_ID, torch_dtype=torch.float16
        )

        self.logger.info(f"Loading SD1.5 base: {SD15_MODEL_ID}")
        self.pipe_cn = StableDiffusionControlNetPipeline.from_pretrained(
            SD15_MODEL_ID,
            controlnet=self.controlnet_openpose,
            torch_dtype=torch.float16,
            safety_checker=None,
        )
        self.pipe_cn.scheduler = UniPCMultistepScheduler.from_config(
            self.pipe_cn.scheduler.config
        )
        self.pipe_cn.enable_xformers_memory_efficient_attention()
        self.pipe_cn.to("cuda")

        self.pipe_i2i = StableDiffusionImg2ImgPipeline.from_pretrained(
            SD15_MODEL_ID,
            torch_dtype=torch.float16,
            safety_checker=None,
        )
        self.pipe_i2i.scheduler = UniPCMultistepScheduler.from_config(
            self.pipe_i2i.scheduler.config
        )
        self.pipe_i2i.enable_xformers_memory_efficient_attention()
        self.pipe_i2i.to("cuda")

        self.logger.info("SD1.5 + ControlNet models loaded on CUDA.")

    # ── Generation ────────────────────────────────────────────────────────────

    def generate_base(self, creature_category: str, positive: str, negative: str) -> Image.Image:
        """Stage 1: txt2img + ControlNet → clean base structure."""
        if creature_category == "quadruped":
            ctrl_img = Image.open(QUAD_ANIMALPOSE_PATH).convert("RGB").resize((IMG_SIZE, IMG_SIZE))
            self.pipe_cn.controlnet = self.controlnet_animal
        else:
            ctrl_img = Image.open(TPOSE_OPENPOSE_PATH).convert("RGB").resize((IMG_SIZE, IMG_SIZE))
            self.pipe_cn.controlnet = self.controlnet_openpose

        with torch.no_grad():
            result = self.pipe_cn(
                prompt=positive,
                negative_prompt=negative,
                image=ctrl_img,
                num_inference_steps=STAGE1_STEPS,
                guidance_scale=STAGE1_CFG,
                controlnet_conditioning_scale=STAGE1_CN_SCALE,
                width=IMG_SIZE,
                height=IMG_SIZE,
            )
        return result.images[0]

    def refine(self, base_img: Image.Image, positive: str, negative: str) -> Image.Image:
        """Stage 2: img2img → add clothing / texture / aura details."""
        init_img = base_img.resize((IMG_SIZE, IMG_SIZE))
        with torch.no_grad():
            result = self.pipe_i2i(
                prompt=positive,
                negative_prompt=negative,
                image=init_img,
                strength=STAGE2_STRENGTH,
                num_inference_steps=STAGE2_STEPS,
                guidance_scale=STAGE2_CFG,
            )
        return result.images[0]

    # ── Task Processing ───────────────────────────────────────────────────────

    def process_task(self, task: dict, r, db) -> None:
        biome_id  = task["biome_id"]
        char_name = task["character_name"]
        char_type = task.get("character_type", "humanoid")

        creature_category = "quadruped" if char_type == "quadruped" else "bipedal"
        templates = CREATURE_PROMPTS.get(char_type, CREATURE_PROMPTS["bipedal"])

        # Stage 1 — always template (structure-only, no custom override)
        s1_pos = build_prompt(templates["stage1"]["positive"], None)
        s1_neg = templates["stage1"]["negative"]

        # Stage 2 — task-supplied custom prompt if provided
        custom = task.get("refine_prompt") or task.get("prompt")
        s2_pos = build_prompt(templates["stage2"]["positive"], custom)
        s2_neg = templates["stage2"]["negative"]

        self.logger.info(f"[{char_name}] Stage1 ({len(s1_pos.split())}w): {s1_pos}")
        self.logger.info(f"[{char_name}] Stage2 ({len(s2_pos.split())}w): {s2_pos}")

        # ── Stage 1: base structure ───────────────────────────────────────────
        self.mongo_update(biome_id, char_name, {
            "generation_stage": "base_gen",
            "status": "generating",
        })
        self.logger.info(f"[{char_name}] Generating base structure...")
        base_img = self.generate_base(creature_category, s1_pos, s1_neg)

        base_key = f"images/{biome_id}/{char_name}_base.png"
        self.upload_image(base_img, base_key)
        self.mongo_update(biome_id, char_name, {
            "generation_stage": "refinement",
            "images.base": base_key,
        })

        # ── Stage 2: detail refinement ────────────────────────────────────────
        self.logger.info(f"[{char_name}] Refining (strength={STAGE2_STRENGTH})...")
        refined_img = self.refine(base_img, s2_pos, s2_neg)

        refined_key = f"images/{biome_id}/{char_name}_refined.png"
        self.upload_image(refined_img, refined_key)
        self.mongo_update(biome_id, char_name, {
            "generation_stage": "complete",
            "status":           "image_complete",
            "images.refined":   refined_key,
            "images.final":     refined_key,
        })

        # ── Push to TRELLIS queue ─────────────────────────────────────────────
        self.push_task(OUTPUT_QUEUE, {
            "task_id":        str(uuid.uuid4()),
            "biome_id":       biome_id,
            "character_name": char_name,
            "character_type": char_type,
            "image_path":     refined_key,
            "timestamp":      time.time(),
        })
        self.logger.info(f"[{char_name}] Done. Pushed to {OUTPUT_QUEUE}.")

        torch.cuda.empty_cache()
