#!/usr/bin/env python3
"""
SD 1.5 Image Worker  (extends BaseWorker)
=========================================
5-stage pipeline per character:

  Stage 0  — Flux Schnell concept (run separately, stored in MongoDB)
  Stage 1  — SD1.5 + Dual ControlNet + img2img (Flux image as init)
               OpenPose 0.9  → locks pose exactly
               Canny   0.65  → locks silhouette from Flux edges
               denoise 0.30  → preserves Flux anatomy, corrects style
  Stage 2  — SD1.5 img2img (denoise 0.35) → add clothing / detail
  Stage 3  — multi-view (future)
  3D       — TRELLIS (reads Stage 2 refined image)

Style direction:
  POSITIVE suffix  : "semi-realistic, 3D game character, stylized realism"
  NEGATIVE always  : "anime, cartoon, cel shading, 2D illustration, manga, flat art"

ControlNet routing:
  bipedal / humanoid → lllyasviel/control_v11p_sd15_openpose  (COCO-18 T-pose)
  quadruped          → huchenlei/animal_openpose               (AP10K-17 skeleton)
                       (falls back to openpose if not available)

Flux concept fallback:
  If no flux_concept image in MongoDB, Stage 1 runs as txt2img + single OpenPose CN.
"""

import io
import os
import time
import uuid

import numpy as np
import torch
from PIL import Image, ImageFilter
from diffusers import (
    ControlNetModel,
    StableDiffusionControlNetPipeline,
    StableDiffusionControlNetImg2ImgPipeline,
    StableDiffusionImg2ImgPipeline,
    UniPCMultistepScheduler,
)

from .base_worker import BaseWorker

os.environ.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")

# ── Model IDs ─────────────────────────────────────────────────────────────────
SD15_MODEL_ID          = "Lykon/DreamShaper"
CONTROLNET_OPENPOSE_ID = "lllyasviel/control_v11p_sd15_openpose"
CONTROLNET_CANNY_ID    = "lllyasviel/control_v11p_sd15_canny"
# AP10K animal skeleton ControlNet
CONTROLNET_ANIMAL_ID   = "huchenlei/animal_openpose"

# ── Reference skeleton images (generated by prepare_controlnet_refs.py) ───────
TPOSE_OPENPOSE_PATH  = os.getenv(
    "TPOSE_OPENPOSE_PATH",
    "/home/ec2-user/controlnet_refs/tpose_openpose.png",
)
QUAD_ANIMALPOSE_PATH = os.getenv(
    "QUAD_ANIMALPOSE_PATH",
    "/home/ec2-user/controlnet_refs/quad_animalpose.png",
)

# ── Generation hyper-params ───────────────────────────────────────────────────
IMG_SIZE = 512   # SD1.5 native — do NOT use 768 to avoid OOM

# Stage 1 — img2img + dual ControlNet (Flux concept as init)
STAGE1_STEPS          = 25
STAGE1_CFG            = 6.5    # slightly lower than pure txt2img (Flux provides structure)
STAGE1_STRENGTH       = 0.30   # low denoise → preserve Flux anatomy
STAGE1_CN_OPENPOSE    = 0.9    # OpenPose locks pose precisely
STAGE1_CN_CANNY       = 0.65   # Canny locks silhouette from Flux image

# Stage 1 fallback (no Flux) — txt2img + single OpenPose CN
STAGE1_CN_SCALE_FALLBACK = 0.85

# Stage 2 — img2img detail pass
STAGE2_STEPS    = 20
STAGE2_CFG      = 7.0
STAGE2_STRENGTH = 0.35   # modest — don't wreck Stage 1 structure

# ── Queue names ───────────────────────────────────────────────────────────────
INPUT_QUEUE  = "sd15_tasks"
OUTPUT_QUEUE = "model_tasks"

# ── Style direction ───────────────────────────────────────────────────────────
# Applied globally to all prompts.
# Keeps output suitable for TRELLIS 3D mesh generation (no 2D flat art).
STYLE_POSITIVE = "semi-realistic, 3D game character, stylized realism, game asset"
STYLE_NEGATIVE = "anime, cartoon, cel shading, 2D illustration, manga, flat art, sketch"
QUALITY_PREFIX = f"best quality, masterpiece, {STYLE_POSITIVE}, "

SHARED_NEGATIVE = (
    f"{STYLE_NEGATIVE}, "
    "background, shadows, text, watermark, blurry, cropped, "
    "extra limbs, deformed, ugly, nsfw"
)

# ── Per-creature prompt templates ─────────────────────────────────────────────
#
# Stage 1: structure only — pose, proportions, silhouette.
#   NO clothing detail (style tokens waste Stage 1 budget and fight ControlNet).
# Stage 2: identity pass — clothing, colour, material, character features.
#
CREATURE_PROMPTS = {

    # ── Bipedal / Humanoid ────────────────────────────────────────────────────
    "bipedal": {
        "stage1": {
            "positive": (
                "young male, lean build, T-pose, arms extended horizontally, "
                "legs straight, front view, full body, white background, flat lighting, "
                "centered, plain robe, relaxed open hands, character sheet"
            ),
            "negative": (
                "room, environment, complex textures, accessories, jewelry, armor, "
                "dynamic pose, flying, floating, aura, glow"
            ),
        },
        "stage2": {
            "positive": (
                "young male cultivator, ash gray linen hanfu robe, crossover collar, "
                "rope belt, half-up topknot, wooden hairpin, dark sharp eyes, "
                "calm expression, faded sect patch on chest, outer disciple, "
                "front view, white background, clean game asset"
            ),
            "negative": (
                "silk, brocade, embroidery, heavy ornament, master robes, "
                "western armor, aura, glow, magic effects"
            ),
        },
    },

    # ── Quadruped ─────────────────────────────────────────────────────────────
    "quadruped": {
        "stage1": {
            "positive": (
                "four-legged lion creature, muscular feline form, "
                "neutral standing pose, side view, "
                "all four paws flat on ground, spine horizontal, tail extended, "
                "full body, white background, flat lighting, centered, creature design sheet"
            ),
            "negative": (
                "room, environment, running, jumping, rearing, human, bipedal, rider, "
                "wings spread, complex textures"
            ),
        },
        "stage2": {
            "positive": (
                "fantastical lion beast, amber golden fur, flame-shaped rust-orange mane, "
                "bone-white spiral horn on forehead, dragon scales on chest and knees, "
                "blue luminous spine markings, dragon whiskers, cloven rear hooves, "
                "tasseled tail, amber slit-pupil eyes, majestic serene expression, "
                "white background, clean game asset"
            ),
            "negative": (
                "mundane lion, regular animal, wings, human figure, rider"
            ),
        },
    },

    # ── Humanoid alias ────────────────────────────────────────────────────────
    "humanoid": {
        "stage1": {
            "positive": (
                "humanoid character, lean build, T-pose, arms extended horizontally, "
                "front view, full body, white background, flat lighting, "
                "centered, plain outfit, relaxed open hands, character sheet"
            ),
            "negative": (
                "room, environment, complex textures, accessories, weapons, "
                "dynamic pose, aura, glow"
            ),
        },
        "stage2": {
            "positive": (
                "humanoid character, detailed fantasy outfit, layered clothing, "
                "front view, white background, clean game asset"
            ),
            "negative": (
                "photorealistic, western armor, aura, glow, magic effects"
            ),
        },
    },
}


# ── Helpers ───────────────────────────────────────────────────────────────────

def build_prompt(template: str, override: str | None, max_tokens: int = 65) -> str:
    """Prepend quality prefix; use override if supplied. Truncate to max_tokens."""
    base  = QUALITY_PREFIX + (override if override else template)
    words = base.split()
    if len(words) * 1.3 > max_tokens:
        words = words[:int(max_tokens / 1.3)]
    return " ".join(words)


def build_negative(template: str, extra: str | None = None) -> str:
    """Combine shared negative with per-creature and optional task-supplied extras."""
    parts = [SHARED_NEGATIVE, template]
    if extra:
        parts.append(extra)
    return ", ".join(p.strip(", ") for p in parts if p.strip())


def extract_canny(img: Image.Image, lo: int = 80, hi: int = 180) -> Image.Image:
    """
    Extract Canny edges for ControlNet conditioning.
    Uses cv2 when available; falls back to PIL FIND_EDGES.
    Returns an RGB image (black bg, white edges) matching controlnet_canny input format.
    """
    img_resized = img.resize((IMG_SIZE, IMG_SIZE)).convert("RGB")
    try:
        import cv2
        arr  = np.array(img_resized)
        gray = cv2.cvtColor(arr, cv2.COLOR_RGB2GRAY)
        # Slight blur to reduce Flux texture noise before Canny
        gray = cv2.GaussianBlur(gray, (5, 5), 0)
        edges = cv2.Canny(gray, lo, hi)
        rgb   = np.stack([edges, edges, edges], axis=-1)
        return Image.fromarray(rgb.astype(np.uint8))
    except ImportError:
        # PIL fallback — less precise but functional
        gray  = img_resized.convert("L")
        edges = gray.filter(ImageFilter.FIND_EDGES)
        edges = edges.point(lambda x: 255 if x > 25 else 0)
        return Image.merge("RGB", [edges, edges, edges])


def download_s3_image(base_worker: "SD15Worker", s3_key: str) -> Image.Image:
    """Download an S3 object and return it as a PIL Image."""
    buf = io.BytesIO()
    base_worker.get_s3().download_fileobj(
        Bucket=base_worker.cfg.S3_BUCKET,
        Key=s3_key,
        Fileobj=buf,
    )
    buf.seek(0)
    return Image.open(buf).convert("RGB")


# ── Worker ────────────────────────────────────────────────────────────────────

class SD15Worker(BaseWorker):
    """SD1.5 + Dual ControlNet two-stage character image generator."""

    worker_name = "SD15Worker"
    input_queue = INPUT_QUEUE

    def __init__(self):
        super().__init__()
        self.controlnet_openpose = None
        self.controlnet_canny    = None
        self.controlnet_animal   = None
        self.pipe_cn             = None   # txt2img + single CN (fallback)
        self.pipe_cn_i2i         = None   # img2img + dual CN  (Flux init)
        self.pipe_i2i            = None   # plain img2img (Stage 2)

    # ── Model Loading ─────────────────────────────────────────────────────────

    def load_models(self):
        self.logger.info("Loading ControlNet models (OpenPose + Canny + Animal)...")

        self.controlnet_openpose = ControlNetModel.from_pretrained(
            CONTROLNET_OPENPOSE_ID, torch_dtype=torch.float16
        )
        self.controlnet_canny = ControlNetModel.from_pretrained(
            CONTROLNET_CANNY_ID, torch_dtype=torch.float16
        )
        try:
            self.controlnet_animal = ControlNetModel.from_pretrained(
                CONTROLNET_ANIMAL_ID, torch_dtype=torch.float16
            )
            self.logger.info("Loaded animal_openpose ControlNet.")
        except Exception:
            self.logger.warning(
                f"Could not load {CONTROLNET_ANIMAL_ID} — falling back to OpenPose for quadrupeds."
            )
            self.controlnet_animal = self.controlnet_openpose

        self.logger.info(f"Loading SD1.5 base: {SD15_MODEL_ID}")

        # Primary pipeline: txt2img + OpenPose CN (fallback when no Flux concept)
        self.pipe_cn = StableDiffusionControlNetPipeline.from_pretrained(
            SD15_MODEL_ID,
            controlnet=self.controlnet_openpose,
            torch_dtype=torch.float16,
            safety_checker=None,
        )
        self.pipe_cn.scheduler = UniPCMultistepScheduler.from_config(
            self.pipe_cn.scheduler.config
        )
        self.pipe_cn.enable_xformers_memory_efficient_attention()
        self.pipe_cn.to("cuda")

        # Dual-CN img2img pipeline — shares UNet with pipe_cn (no extra VRAM)
        # Override controlnet to [openpose, canny] list for dual conditioning.
        components = dict(self.pipe_cn.components)
        components["controlnet"] = [self.controlnet_openpose, self.controlnet_canny]
        self.pipe_cn_i2i = StableDiffusionControlNetImg2ImgPipeline(**components)
        self.pipe_cn_i2i.scheduler = UniPCMultistepScheduler.from_config(
            self.pipe_cn_i2i.scheduler.config
        )

        # Plain img2img — Stage 2 (shares UNet, no extra VRAM)
        # Exclude 'controlnet' — StableDiffusionImg2ImgPipeline doesn't accept it
        i2i_components = {k: v for k, v in self.pipe_cn.components.items() if k != "controlnet"}
        self.pipe_i2i = StableDiffusionImg2ImgPipeline(**i2i_components)
        self.pipe_i2i.scheduler = UniPCMultistepScheduler.from_config(
            self.pipe_i2i.scheduler.config
        )

        self.logger.info(
            "SD1.5 loaded: pipe_cn + pipe_cn_i2i (dual CN) + pipe_i2i (Stage 2). "
            "UNet shared — no duplicate VRAM."
        )

    # ── Generation ────────────────────────────────────────────────────────────

    def generate_base(
        self,
        creature_category: str,
        positive: str,
        negative: str,
        flux_concept_img: Image.Image | None = None,
    ) -> Image.Image:
        """
        Stage 1 — produce clean posed structure.

        If flux_concept_img provided:
          img2img + dual ControlNet (OpenPose + Canny)
          → OpenPose locks pose, Canny locks Flux silhouette
          → denoise 0.30 preserves Flux anatomy

        Fallback (no Flux):
          txt2img + single OpenPose CN  (original behaviour)
        """
        is_quad = (creature_category == "quadruped")
        pose_cn = self.controlnet_animal if is_quad else self.controlnet_openpose

        # Pose skeleton reference (always needed)
        pose_ref_path = QUAD_ANIMALPOSE_PATH if is_quad else TPOSE_OPENPOSE_PATH
        if not os.path.exists(pose_ref_path):
            self.logger.warning(f"Pose ref not found: {pose_ref_path} — generation may drift")
        openpose_img = (
            Image.open(pose_ref_path).convert("RGB").resize((IMG_SIZE, IMG_SIZE))
            if os.path.exists(pose_ref_path)
            else Image.new("RGB", (IMG_SIZE, IMG_SIZE), 0)
        )

        if flux_concept_img is not None:
            # ── Dual CN img2img path (preferred) ─────────────────────────────
            self.logger.info(
                f"Stage 1 — img2img + dual CN  "
                f"[OpenPose={STAGE1_CN_OPENPOSE}  Canny={STAGE1_CN_CANNY}  "
                f"denoise={STAGE1_STRENGTH}]"
            )
            init_img  = flux_concept_img.resize((IMG_SIZE, IMG_SIZE))
            canny_img = extract_canny(flux_concept_img)

            # Swap pipe_cn_i2i's controlnet to quad-appropriate CN for pose
            self.pipe_cn_i2i.controlnet = [pose_cn, self.controlnet_canny]

            with torch.no_grad():
                result = self.pipe_cn_i2i(
                    prompt=positive,
                    negative_prompt=negative,
                    image=init_img,
                    control_image=[openpose_img, canny_img],
                    strength=STAGE1_STRENGTH,
                    num_inference_steps=STAGE1_STEPS,
                    guidance_scale=STAGE1_CFG,
                    controlnet_conditioning_scale=[STAGE1_CN_OPENPOSE, STAGE1_CN_CANNY],
                    width=IMG_SIZE,
                    height=IMG_SIZE,
                )
        else:
            # ── Fallback: txt2img + single OpenPose CN ────────────────────────
            self.logger.info(
                f"Stage 1 — txt2img + single CN fallback  [scale={STAGE1_CN_SCALE_FALLBACK}]"
            )
            self.pipe_cn.controlnet = pose_cn
            with torch.no_grad():
                result = self.pipe_cn(
                    prompt=positive,
                    negative_prompt=negative,
                    image=openpose_img,
                    num_inference_steps=STAGE1_STEPS,
                    guidance_scale=STAGE1_CFG,
                    controlnet_conditioning_scale=STAGE1_CN_SCALE_FALLBACK,
                    width=IMG_SIZE,
                    height=IMG_SIZE,
                )

        return result.images[0]

    def refine(self, base_img: Image.Image, positive: str, negative: str) -> Image.Image:
        """Stage 2 — img2img detail pass (clothing, texture, colour)."""
        init_img = base_img.resize((IMG_SIZE, IMG_SIZE))
        with torch.no_grad():
            result = self.pipe_i2i(
                prompt=positive,
                negative_prompt=negative,
                image=init_img,
                strength=STAGE2_STRENGTH,
                num_inference_steps=STAGE2_STEPS,
                guidance_scale=STAGE2_CFG,
            )
        return result.images[0]

    # ── Task Processing ───────────────────────────────────────────────────────

    def process_task(self, task: dict, r, db) -> None:
        biome_id  = task["biome_id"]
        char_name = task["character_name"]
        char_type = task.get("character_type", "humanoid")

        creature_category = "quadruped" if char_type == "quadruped" else "bipedal"
        templates = CREATURE_PROMPTS.get(char_type, CREATURE_PROMPTS["bipedal"])

        # ── Build prompts ─────────────────────────────────────────────────────
        # Stage 1 — task fields win, then fall back to creature template
        s1_pos = task.get("stage1_prompt") or build_prompt(
            templates["stage1"]["positive"], None
        )
        s1_neg = build_negative(
            task.get("stage1_negative") or templates["stage1"]["negative"]
        )

        # Stage 2 — priority: stage2_prompt > refine_prompt > prompt > template
        s2_pos = build_prompt(
            templates["stage2"]["positive"],
            task.get("stage2_prompt") or task.get("refine_prompt") or task.get("prompt"),
        )
        s2_neg = build_negative(
            task.get("stage2_negative") or templates["stage2"]["negative"]
        )

        self.logger.info(f"[{char_name}] Stage1 prompt: {s1_pos[:120]}")
        self.logger.info(f"[{char_name}] Stage1 negative: {s1_neg[:80]}")
        self.logger.info(f"[{char_name}] Stage2 prompt: {s2_pos[:120]}")

        # ── Fetch Flux concept image from MongoDB → S3 ────────────────────────
        flux_concept_img = None
        try:
            biome_doc = db.biomes.find_one({"_id": biome_id})
            char_doc  = (
                biome_doc
                .get("possible_structures", {})
                .get("characters", {})
                .get(char_name, {})
            ) if biome_doc else {}

            flux_key = (
                char_doc.get("flux_concept", {}).get("image_key")
                or char_doc.get("images", {}).get("flux_concept")
            )
            if flux_key:
                self.logger.info(f"[{char_name}] Downloading Flux concept: {flux_key}")
                flux_concept_img = download_s3_image(self, flux_key)
                self.logger.info(f"[{char_name}] Flux concept loaded ({flux_concept_img.size})")
            else:
                self.logger.info(
                    f"[{char_name}] No Flux concept in MongoDB — Stage 1 fallback (txt2img+CN)"
                )
        except Exception as e:
            self.logger.warning(f"[{char_name}] Could not load Flux concept: {e} — using fallback")

        # ── Stage 1: structure lock ───────────────────────────────────────────
        self.mongo_update(biome_id, char_name, {
            "status":           "generating",
            "generation_stage": "stage1_base",
            "stage1.prompt":    s1_pos,
            "stage1.negative":  s1_neg,
            "stage1.status":    "generating",
        })
        self.logger.info(f"[{char_name}] Stage 1 — ControlNet ({creature_category})...")
        base_img = self.generate_base(creature_category, s1_pos, s1_neg, flux_concept_img)

        base_key    = f"images/{biome_id}/{char_name}_base.png"
        s3_base_url = self.s3_public_url(base_key)
        self.upload_image(base_img, base_key)
        self.mongo_update(biome_id, char_name, {
            "generation_stage": "stage2_refine",
            "stage1.status":    "complete",
            "stage1.image_key": base_key,
            "stage1.image_url": s3_base_url,
            "images.base":      base_key,
        })
        self.logger.info(f"[{char_name}] Stage 1 done → {base_key}")

        torch.cuda.empty_cache()

        # ── Stage 2: detail refinement ────────────────────────────────────────
        self.mongo_update(biome_id, char_name, {
            "stage2.prompt":   s2_pos,
            "stage2.negative": s2_neg,
            "stage2.status":   "generating",
        })
        self.logger.info(f"[{char_name}] Stage 2 — img2img refine (strength={STAGE2_STRENGTH})...")
        refined_img = self.refine(base_img, s2_pos, s2_neg)

        refined_key    = f"images/{biome_id}/{char_name}_refined.png"
        s3_refined_url = self.s3_public_url(refined_key)
        self.upload_image(refined_img, refined_key)
        self.mongo_update(biome_id, char_name, {
            "generation_stage": "image_complete",
            "status":           "image_complete",
            "stage2.status":    "complete",
            "stage2.image_key": refined_key,
            "stage2.image_url": s3_refined_url,
            "images.refined":   refined_key,
            "images.final":     refined_key,   # TRELLIS reads this key
            "image_url":        s3_refined_url, # top-level for Gradio viewer
        })
        self.logger.info(f"[{char_name}] Stage 2 done → {refined_key}")

        torch.cuda.empty_cache()

        # ── Push to TRELLIS queue ─────────────────────────────────────────────
        self.push_task(OUTPUT_QUEUE, {
            "task_id":        str(uuid.uuid4()),
            "biome_id":       biome_id,
            "character_name": char_name,
            "character_type": char_type,
            "image_path":     refined_key,
            "timestamp":      time.time(),
        })
        self.logger.info(f"[{char_name}] Complete → pushed to {OUTPUT_QUEUE}.")
